# Generated by Django 4.1 on 2022-09-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_carro"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carro",
            new_name="Veiculo",
        ),
    ]
